# Generated by Django 5.1.4 on 2025-01-02 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('nacionalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('endereco', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('sub_titulo', models.CharField(max_length=20, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestismo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('prazo', models.DateField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cliente')),
                ('idlivro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
            ],
        ),
    ]
