# Generated by Django 5.1.4 on 2025-01-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestismo',
            name='prazo',
        ),
    ]
