# Generated by Django 5.1.4 on 2025-01-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.SmallIntegerField()),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
